# Generated by Django 5.1.2 on 2024-11-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_asignaturas_asi_curs_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionesTipos',
            fields=[
                ('ANOT_T_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de tipo')),
                ('ANOT_T_NOMBRE', models.CharField(max_length=50, verbose_name='Nombre tipo anotación')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Anotaciones',
            fields=[
                ('ANOT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ANOT_TITULO', models.TextField(blank=True, max_length=100, null=True, verbose_name='Titulo anotación')),
                ('ANOT_DESCRIPCION', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('ANOT_FECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ANOT_ASIG_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.asignaturas', verbose_name='Asignatura')),
                ('ANOT_CURS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cursos', verbose_name='Curso')),
                ('ANOT_PEPE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personasperfiles', verbose_name='Alumno')),
                ('ANOT_ANOT_T_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotaciones.anotacionestipos', verbose_name='Tipo de Anotación')),
            ],
            options={
                'verbose_name': 'Anotación',
                'verbose_name_plural': 'Anotaciones',
                'ordering': ['-ANOT_FECHACREACION'],
            },
        ),
    ]
