# Generated by Django 5.1.2 on 2024-10-11 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PERS_NOMBRECOMPLETO', models.CharField(blank=True, max_length=60, null=True, verbose_name='Pers_nombrecompleto')),
                ('PERS_FECHANAC', models.DateField(blank=True, max_length=9, null=True, verbose_name='Pers_fechanac')),
                ('PERS_RUT', models.CharField(blank=True, max_length=9, null=True, verbose_name='Pers_rut')),
                ('PERS_TELEFONO', models.CharField(blank=True, max_length=14, null=True, verbose_name='Pers_telefono')),
                ('PERS_DIRECCION', models.CharField(blank=True, max_length=40, null=True, verbose_name='Pers_direccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
