# Generated by Django 5.1.2 on 2024-10-14 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('PERF_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de perfiles')),
                ('PERF_NOMBRE', models.CharField(max_length=50, verbose_name='Perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='PersonasPerfiles',
            fields=[
                ('PEPE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PEPE_FECHACREACION', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('PEPE_PERF_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_perfiles', to='accounts.perfiles')),
                ('PEPE_PERS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='accounts.personas')),
            ],
            options={
                'verbose_name': 'Perfil de Persona',
                'verbose_name_plural': 'Perfiles de Personas',
                'ordering': ['PEPE_ID'],
            },
        ),
    ]
