# Generated by Django 5.1.2 on 2024-10-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfiles_personasperfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='PERF_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de perfiles'),
        ),
    ]
