# Generated by Django 5.1.2 on 2024-10-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cursos_personasperfiles_pepe_curs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='PERS_DIRECCION',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='PERS_FECHANAC',
            field=models.DateField(blank=True, max_length=9, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='PERS_NOMBRECOMPLETO',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='PERS_RUT',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='PERS_TELEFONO',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefono'),
        ),
    ]
