# Generated by Django 5.1.2 on 2024-10-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personasperfiles_pepe_pepe_responsable_asignaturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='ASI_CURS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='accounts.cursos', verbose_name='Curso'),
        ),
    ]
