# Generated by Django 5.1.2 on 2024-10-19 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_personasperfiles_pepe_pepe_responsable_asignaturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('NOTA_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NOTA_VALOR', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('NOTA_FECHACREACION', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('NOTA_DESCRIPCION', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('NOTA_CURS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cursos', verbose_name='Curso')),
                ('NOTA_PEPE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personasperfiles', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-NOTA_FECHACREACION'],
            },
        ),
    ]
