# Generated by Django 5.1.2 on 2024-10-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_asignaturas_asi_curs_id'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='NOTA_ASIG_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.asignaturas', verbose_name='Asignatura'),
        ),
    ]
