# Generated by Django 5.1.2 on 2024-10-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RemoveField(
            model_name='notas',
            name='NOTA_DESCRIPCION',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='NOTA_VALOR',
        ),
        migrations.AddField(
            model_name='notas',
            name='NOTA_VALOR1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1'),
        ),
        migrations.AddField(
            model_name='notas',
            name='NOTA_VALOR2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2'),
        ),
        migrations.AddField(
            model_name='notas',
            name='NOTA_VALOR3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3'),
        ),
        migrations.AddField(
            model_name='notas',
            name='NOTA_VALOR4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 4'),
        ),
        migrations.AddField(
            model_name='notas',
            name='NOTA_VALOR5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 5'),
        ),
        migrations.AddField(
            model_name='notas',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio'),
        ),
    ]
