# Generated by Django 5.1.2 on 2024-10-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_notas_nota_asig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='NOTA_FECHACREACION',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
