# Generated by Django 5.1.2 on 2024-10-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_personas_pers_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionesTipos',
            fields=[
                ('PUTI_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de tipo')),
                ('PUTI_NOMBRE', models.CharField(max_length=50, verbose_name='Nombre tipo publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('PUBL_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de publicación')),
                ('PUBL_TITULO', models.CharField(max_length=200, verbose_name='Título de la publicación')),
                ('PUBL_DESCRIPCIO', models.TextField(verbose_name='Descripción publicación')),
                ('PUBL_IMAGEN', models.ImageField(blank=True, null=True, upload_to='publicaciones/', verbose_name='Imagen')),
                ('PUBL_FECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('PUBL_PEPE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personasperfiles', verbose_name='Autor')),
                ('PUBL_PUTI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muro.publicacionestipos', verbose_name='Tipo de publicación')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-PUBL_FECHACREACION'],
            },
        ),
    ]
