# Generated by Django 5.1.2 on 2024-11-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotaciones',
            name='ANOT_ANOT_T_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anotaciones.anotacionestipos', verbose_name='Tipo de Anotación'),
        ),
    ]
