# Generated by Django 5.1.2 on 2024-10-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_asignaturas_asi_curs_id'),
        ('sino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('ASIS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ASIS_FECHA', models.DateField(auto_now_add=True)),
                ('ASIS_ASIG_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.asignaturas')),
                ('ASIS_CURS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cursos')),
                ('ASIS_PEPE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personasperfiles')),
                ('ASIS_SINO_PRESENTACERTIFICADO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='sino.sino')),
                ('ASIS_SINO_PRESENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presente', to='sino.sino')),
            ],
        ),
    ]
