# Generated by Django 5.1.2 on 2024-11-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_asignaturas_asi_curs_id'),
        ('muro', '0002_alter_publicacionestipos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones_Comentarios',
            fields=[
                ('PUCO_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de comentario')),
                ('PUCO_COMENTARIO', models.CharField(max_length=200, verbose_name='comentario')),
                ('PUCO_FECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('PUCO_PEPE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personasperfiles', verbose_name='Autor')),
                ('PUCO_PUBL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muro.publicaciones', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-PUCO_FECHACREACION'],
            },
        ),
    ]
