# Generated by Django 5.1.2 on 2024-10-15 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfiles_perf_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('CURS_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de curso')),
                ('CURS_NOMBRE', models.CharField(max_length=50, verbose_name='Nombre curso')),
                ('CURS_SALA', models.IntegerField(verbose_name='Numero de sala')),
                ('CURS_ANNO', models.IntegerField(verbose_name='Año de curso')),
            ],
        ),
        migrations.AddField(
            model_name='personasperfiles',
            name='PEPE_CURS_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='accounts.cursos'),
        ),
    ]
