# Generated by Django 5.1.2 on 2024-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sino',
            name='SINO_NOMBRE',
            field=models.CharField(max_length=25),
        ),
    ]
